#:schema https://raw.githubusercontent.com/razterizer/forge/main/schemas/forge.recipe.schema.json

[project]
name = "AudioLibSwitcher_OpenAL"
version = "1.0.0"
type = "header_only"
cpp_std = 20

[sources]
paths = []
public_headers = ["include/AudioLibSwitcher/AudioLibSwitcher_OpenAL.h"]

[build]
number = 6

[release]
build_number_format = "dotted"

[dependencies]
AudioLibSwitcher = { path = "AudioLibSwitcher" }
3rdparty_OpenAL = { path = "../3rdparty_OpenAL" }

[profile.workflow-release.dependencies]
AudioLibSwitcher = { github = "razterizer/AudioLibSwitcher", version = "1.0.0+build.1" }
3rdparty_OpenAL = { github = "razterizer/3rdparty_OpenAL", version = "1.0.0+build.3" }

[profile.workflow-release.build]
configuration = "Release"

[profile.Debug.build]
configuration = "Debug"
defines = ["DEBUG=1"]

[profile.Release.build]
configuration = "Release"
